### ISSUE TITLE
Add paged attention kernels for the Llama model architecture

### ISSUE THREAD

**Issue by jorgeantonio21** [atoma-network/atoma-node-inference#1]
Following the paged attention [paper](https://arxiv.org/pdf/2309.06180), add cuda kernels for the Llama model. Cuda kernels for the Llama architecture have been widely implemented in the open source community. 

Moreover, paged attention kernels can be found in the original vLLM implementation [here](https://github.com/vllm-project/vllm/tree/main/csrc). Of special interest for us is the cuda implementation in [attention_kernels.cu](https://github.com/vllm-project/vllm/blob/main/csrc/attention/attention_kernels.cu), which implements the attention logic using the pagination algorithms (described in the reference paper above).

**NOTE: Issue 1 must be completed in order to progress onto issues 2,3.4**

**Comment by jorgeantonio21** [comment]
In order to further guide the work on this issue, we suggest the following:

[ ] - Get familiar with the main ideas in the [paper](https://arxiv.org/pdf/2309.06180).
[ ] - Understand how the Llama architecture works, at a high level (how KV cache is used, how attention is calculated, etc). 
[ ] - Get familiar with the cuda code in [attention_kernels.cu](https://github.com/vllm-project/vllm/blob/main/csrc/attention/attention_kernels.cu).
[ ] - Once you are familiar with the code in [attention_kernels.cu](https://github.com/vllm-project/vllm/blob/main/csrc/attention/attention_kernels.cu), you can try your own implementation, or simply add the file here. Make sure, you include all necessary dependencies.
[ ] - Create a new PR, tagging this issue, and explaining briefly your understanding of paged attention and how it can be used to optimized Llama serving AI inference.

**Comment by RajeshRk18** [comment]
Hey @jorgeantonio21! Shall I take up this issue? I will follow every step as shown above

**Comment by jorgeantonio21** [comment]
@RajeshRk18 please feel free to tackle this one down. Also, if any questions/issues arise while tackling this one feel free to ping me

**Comment by g4titanx** [comment]
hello, I would love to work on this too

**Comment by fishonamos** [comment]
Hi @jorgeantonio21. I will love to work on this.

**Comment by Josh-121** [comment]
Pls assign if available
