### ISSUE TITLE
Integrate Llama cuda kernels with Candle

### ISSUE THREAD

**Issue by jorgeantonio21** [atoma-network/atoma-node-inference#2]
This issue goal is to integrate the paged attention cuda kernels requested in #1 with the candle ML framework. We suggest following the code in [here](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/llama.rs). The idea is to replace the attention kernels in the previous link, with the newly added paged attention algorithms that were added in #1 .

**Comment by jorgeantonio21** [comment]
In order to complete this issue, we suggest following the steps:

- [ ] Understand how the [candle](https://github.com/huggingface/candle) implementation leverages [cudarc](https://github.com/coreylowman/cudarc) to load cuda kernels, in order to run fast AI inference on NVIDIA GPUs.
- [ ] Identify each of the cuda kernels used in the implementation of the candle's Llama model, in [here](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/llama.rs).
- [ ] Once you have identified which kernels have been used, proceed into identifying how to introduce the paged attention kernels in #1 for the Llama model. You should replace the candle's own attention kernels with the paged attention ones.
- [ ] Understand if there are other kernels that need to be replaced.
- [ ] Feel free to add as many tests as you think is necessary to validate the hypothesis you have come into, while trying to resolve the steps above.
- [ ] Open a PR, explaining how you changed the original candle implementation of the Llama model in order to introduce paged attention into it.

**Comment by Josh-121** [comment]
Would love to work on this. Please assign

**Comment by JuanPabloRodriguezC** [comment]
Hello @jorgeantonio21! I’m Juan, new to OSS. I like this project since I have experience with training models. I would like to tackle this issue following the guidelines provided.

**Comment by No-bodyq** [comment]
Hey @jorgeantonio21 Can I hop on this once it's available

**Comment by jorgeantonio21** [comment]
@No-bodyq @JuanPabloRodriguezC @Josh-121 assigned you all. Notice that you need to tackle #1 before finishing this one, as it requires the cuda kernels to be added..
