### ISSUE TITLE
Add a Llama inference main file

### ISSUE THREAD

**Issue by jorgeantonio21** [atoma-network/atoma-node-inference#3]
In order to have full Llama inference, one needs to loop over each generated token. Once the issues #1 and #2 have been resolved, we suggest following the implementation in [here](https://github.com/huggingface/candle/tree/main/candle-examples/examples/llama) to implement the full inference looping.

**Comment by Josh-121** [comment]
Available? Would love to work on this

**Comment by jedstroke** [comment]
@jorgeantonio21 I could tackle this

**Comment by jorgeantonio21** [comment]
@Josh-121 and @jedstroke assigned you both. Notice that you need to tackle both issues #1 and #2 before starting this one..
