### ISSUE TITLE
Test the paged attention vs the original candle implementations

### ISSUE THREAD

**Issue by jorgeantonio21** [atoma-network/atoma-node-inference#4]
Provide a few examples, to compare the Llama generation relying on the paged attention algorithms vs the original candle Llama implementation.

**Comment by jorgeantonio21** [comment]
We suggest following:

- [ ] Once you have resolved #3, please create a script that can run the original candle Llama implementation, as well as yours. 
- [ ] Provide a few prompt examples. 
- [ ] Run these prompt examples on each of the implementations, using your script. 
- [ ] Record the outputs of each inference and compare them. 
- [ ] You should check if the outputs are exactly the same, and if not provide a hint of which outputs you think are more accurate as an answer to the input prompts.
- [ ] Open a PR, explaining each of the steps above.

**Comment by Josh-121** [comment]
Available? Please assign

**Comment by jedstroke** [comment]
@jorgeantonio21 Yo, let me tackle this issue. I got @WillNovus on my team

**Comment by jorgeantonio21** [comment]
@Josh-121 @jedstroke assigned you both ! Good luck with it (want to highlight this issue depends on the previous ones #1, #2 and #3).

**Comment by jedstroke** [comment]
Thanks @jorgeantonio21
